global:
  scrape_interval: 15s

scrape_configs:
  - job_name: app
    basic_auth:
      username: prometheus
      password: "123"
    static_configs:
      - targets:
          - host.docker.internal:8080 #app runs on host machine, but Prometheus runs in Docker