global:
  scrape_interval: 15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds

scrape_configs:
  - job_name: app
    basic_auth:
      username: prometheus
      password: "123"
    static_configs:
      - targets:
          - host.docker.internal:8080 #app runs on host machine, but Prometheus runs in Docker

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - host.docker.internal:9093